name: Exemplo de Workflow

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  notifi_discord:
    runs-on: ubuntu-latest
    steps:
    - name: Enviar notificação para o Slack
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        # Comando para enviar uma notificação para o discord usando o valor do segredo
        curl -X POST -H "Content-Type: multipart/form-data" -F "content=teste de envio" "$DISCORD_WEBHOOK_URL"
